name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    uses: Kysect/.github/.github/workflows/dotnet-releaser.yaml@master
    with:
      dotnet-version: '8.0'
      install-dotnet-aspire: true
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}